Project/Code/SCAP/Controllers/PareceresController.cs
using System;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SCAP.Extensions;
using SCAP.Models;
using SCAP.Notifications;
using SCAP.Services.Interfaces;
using SCAP.ViewModels;

namespace SCAP.Controllers
{
    [Authorize(Roles = "Secretario, Professor"), ActiveUser]
    public class PareceresController : BaseController
    {
        private readonly IAfastamentoService _afastamentoService;
        private readonly IParecerService _parecerService;

        public PareceresController(IAfastamentoService afastamentoService, IParecerService parecerService,
            IUserService<Pessoa> userService, IMapper mapper, INotificator notificator)
            : base(userService, mapper, notificator)
        {
            _afastamentoService = afastamentoService;
            _parecerService = parecerService;
        }

        [Route("afastamentos/{afastamentoId:guid}/pareceres/novo")]
        public IActionResult Create(Guid afastamentoId)
        {
            var afastamento = _afastamentoService.Get(afastamentoId);
            
            if (afastamento == null)
            {
                return NotFound();
            }

            if (User.IsInRole("Professor"))
            {
                return PartialView("Modals/_CreateParecerModal", new ParecerViewModel { AfastamentoId = afastamento.Id });
            }

            if (User.IsInRole("Secretario"))
            {
                return SecretarioModal(afastamento);
            }

            return Forbid();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("afastamentos/{afastamentoId:guid}/pareceres/novo")]
        public IActionResult Create(Guid afastamentoId, ParecerViewModel parecerViewModel)
        {
            if (afastamentoId != parecerViewModel.AfastamentoId)
            {
                return NotFound();
            }

            if (User.IsInRole("Professor"))
            {
                return AddParecerProfessor(parecerViewModel);
            }

            if (User.IsInRole("Secretario"))
            {
                return AddParecerSecretario(parecerViewModel);
            }

            return Forbid();
        }

        private IActionResult AddParecerProfessor(ParecerViewModel parecerViewModel)
        {
            var afastamento = _afastamentoService.Get(parecerViewModel.AfastamentoId);

            if (afastamento == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return PartialView("Modals/_CreateParecerModal", parecerViewModel);
            }

            parecerViewModel.ProfessorId = UserService.GetId(User);

            _parecerService.Add(Mapper.Map<Parecer>(parecerViewModel));

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_CreateParecerModal", parecerViewModel);
            }

            TempData["Success"] = "Parecer deferido com sucesso!";

            return JsonOk(Url.Action("Details", "Afastamentos", new { id = afastamento.Id }));
        }

        private IActionResult AddParecerSecretario(ParecerViewModel parecerViewModel)
        {
            var afastamento = _afastamentoService.Get(parecerViewModel.AfastamentoId);

            if (afastamento == null)
            {
                return NotFound();
            }

            ModelState.Remove("DocumentoParecer.Titulo");

            if (!ModelState.IsValid)
            {
                return SecretarioModal(afastamento);
            }

            var file = parecerViewModel.DocumentoParecer.File;
            
            if (parecerViewModel.Julgamento == 1)
            {
                if (afastamento.Situacao == SituacaoPedidoAfastamento.AprovadoDI)
                {
                    _afastamentoService.AprovarCT(afastamento.Id, file);
                }
                else if (afastamento.Situacao == SituacaoPedidoAfastamento.AprovadoCT)
                {
                    _afastamentoService.AprovarPRPPG(afastamento.Id, file);
                }
                else
                {
                    return Forbid();
                }
            }
            else if (parecerViewModel.Julgamento == 2)
            {
                _afastamentoService.Reprovar(afastamento.Id, file);
            }
            else
            {
                return Forbid();
            }

            if (ErrorsOccurred())
            {
                return SecretarioModal(afastamento);
            }

            TempData["Success"] = "Parecer deferido com sucesso!";

            return JsonOk(Url.Action("Details", "Afastamentos", new { id = afastamento.Id }));
        }

        private IActionResult SecretarioModal(Afastamento afastamento)
        {
            string modal;

            if (afastamento.Situacao == SituacaoPedidoAfastamento.AprovadoDI)
            {
                modal = "_CreateParecerCTModal";
            }
            else if (afastamento.Situacao == SituacaoPedidoAfastamento.AprovadoCT)
            {
                modal = "_CreateParecerPRPPGModal";
            }
            else
            {
                return Forbid();
            }

            return PartialView($"Modals/{modal}", new ParecerViewModel
            {
                AfastamentoId = afastamento.Id,
                DocumentoParecer = new DocumentoViewModel
                {
                    AfastamentoId = afastamento.Id
                }
            });
        }
    }
}

Project/Code/SCAP/Views/Pareceres/Modals/_CreateParecerCTModal.cshtml
@model SCAP.ViewModels.ParecerViewModel

<form method="post" enctype="multipart/form-data" asp-controller="Pareceres" asp-action="Create">
    <div class="modal-header">
        <h5 class="modal-title">Emitir parecer do CT</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <input type="hidden" asp-for="AfastamentoId" />
        <div class="form-group">
            <label asp-for="Julgamento" class="control-label"></label><br />
            <input type="radio" asp-for="Julgamento" value="1" /> Favorável<br />
            <input type="radio" asp-for="Julgamento" value="2" /> Desfavorável<br />
            <span asp-validation-for="Julgamento" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="DocumentoParecer.AfastamentoId" />
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="new-parecer-doc" asp-for="DocumentoParecer.File" />
                <label data-browse="Procurar" class="custom-file-label" for="new-parecer-doc">Selecione um arquivo</label>
                <span asp-validation-for="DocumentoParecer.File" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Emitir" />
    </div>
</form>

Project/Code/SCAP/Views/Pareceres/Modals/_CreateParecerModal.cshtml
@model SCAP.ViewModels.ParecerViewModel

<form method="post" enctype="multipart/form-data" asp-controller="Pareceres" asp-action="Create">
    <div class="modal-header">
        <h5 class="modal-title">Emitir parecer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <input type="hidden" asp-for="AfastamentoId" />
        <div class="form-group">
            <label asp-for="Julgamento" class="control-label"></label><br />
            <input type="radio" asp-for="Julgamento" value="1" /> Favorável<br />
            <input type="radio" asp-for="Julgamento" value="2" /> Desfavorável<br />
            <span asp-validation-for="Julgamento" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Justificativa" class="control-label"></label>
            <textarea class="form-control" asp-for="Justificativa"></textarea>
            <span asp-validation-for="Justificativa" class="text-danger"></span>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Emitir" />
    </div>
</form>

Project/Code/SCAP/Views/Pareceres/Modals/_CreateParecerPRPPGModal.cshtml
@model SCAP.ViewModels.ParecerViewModel

<form method="post" enctype="multipart/form-data" asp-controller="Pareceres" asp-action="Create">
    <div class="modal-header">
        <h5 class="modal-title">Emitir parecer da PRPPG</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <input type="hidden" asp-for="AfastamentoId" />
        <div class="form-group">
            <label asp-for="Julgamento" class="control-label"></label><br />
            <input type="radio" asp-for="Julgamento" value="1" /> Favorável<br />
            <input type="radio" asp-for="Julgamento" value="2" /> Desfavorável<br />
            <span asp-validation-for="Julgamento" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="DocumentoParecer.AfastamentoId" />
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="new-parecer-doc" asp-for="DocumentoParecer.File" />
                <label data-browse="Procurar" class="custom-file-label" for="new-parecer-doc">Selecione um arquivo</label>
                <span asp-validation-for="DocumentoParecer.File" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Emitir" />
    </div>
</form>