Project/Code/SCAP/Models/Afastamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SCAP.Models
{
    public class Afastamento : Entity
    {
        [Required]
        public DateTime DataPedido { get; set; }

        [Required]
        public DateTime DataInicio { get; set; }

        [Required]
        public DateTime DataFim { get; set; }

        [Required]
        public SituacaoPedidoAfastamento Situacao { get; set; }

        [Required]
        public TipoAfastamento TipoAfastamento { get; set; }

        [StringLength(1024)]
        public string Motivo { get; set; }

        [Required]
        public Onus Onus { get; set; }

        [Required]
        public DateTime DataInicioEvento { get; set; }

        [Required]
        public DateTime DataFimEvento { get; set; }

        [Required]
        [StringLength(256)]
        public string NomeEvento { get; set; }

        /* EF Associations */
        public IEnumerable<Parecer> Pareceres { get; set; }
        public IEnumerable<Documento> Documentos { get; set; }

        [ForeignKey("RelatorId")]
        public Professor Relator { get; set; }
        public string RelatorId { get; set; }

        [ForeignKey("SolicitanteId")]
        public Professor Solicitante { get; set; }
        [Required]
        public string SolicitanteId { get; set; }
    }
}

Project/Code/SCAP/ViewModels/AfastamentoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace SCAP.ViewModels
{
    public class AfastamentoViewModel
    {
        [Key]
        [HiddenInput]
        [DisplayName("Código do pedido")]
        public Guid Id { get; set; }

        [DisplayName("Data e hora do pedido")]
        [ScaffoldColumn(false)]
        public DateTime DataPedido { get; set; }
        
        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Data de início")]
        public DateTime DataInicio { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Data de fim")]
        public DateTime DataFim { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Range(1, 9, ErrorMessage = "O campo {0} deve conter uma opção válida.")]
        [DisplayName("Situação atual")]
        public int Situacao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Range(1, 2, ErrorMessage = "O campo {0} deve conter uma opção válida.")]
        [DisplayName("Tipo de afastamento")]
        public int TipoAfastamento { get; set; }

        [StringLength(1024, ErrorMessage = "O campo {0} deve ter no máximo {1} caracteres.")]
        [DisplayName("Motivo do afastamento")]
        public string Motivo { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [Range(1, 3 , ErrorMessage = "O campo {0} deve conter uma opção válida.")]
        [DisplayName("Tipo de ônus")]
        public int Onus { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Data de início do evento")]
        public DateTime DataInicioEvento { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [DisplayName("Data de fim do evento")]
        public DateTime DataFimEvento { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório.")]
        [StringLength(256, MinimumLength = 2, ErrorMessage = "O campo {0} deve ter no mínimo {2} e no máximo {1} caracteres.")]
        [DisplayName("Nome do evento")]
        public string NomeEvento { get; set; }
        
        public List<ParecerViewModel> Pareceres { get; set; }
        public List<DocumentoViewModel> Documentos { get; set; }
        
        [HiddenInput]
        [DisplayName("Relator")]
        public string RelatorId { get; set; }
        public UserViewModel Relator { get; set; }

        [HiddenInput]
        [DisplayName("Solicitante")]
        public string SolicitanteId { get; set; }
        public UserViewModel Solicitante { get; set; }

        [DisplayName("Decisão")]
        [Range(1, 2, ErrorMessage = "O campo {0} deve conter uma opção válida.")]
        public int DecisaoReuniao { get; set; }
    }
}

Project/Code/SCAP/Controllers/AfastamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;
using SCAP.Extensions;
using SCAP.Models;
using SCAP.Notifications;
using SCAP.Services.Interfaces;
using SCAP.ViewModels;

namespace SCAP.Controllers
{
    [Authorize(Roles = "Secretario, Professor"), ActiveUser]
    public class AfastamentosController : BaseController
    {
        private readonly IAfastamentoService _afastamentoService;
        private readonly IProfessorService _professorService;
        private readonly ISecretarioService _secretarioService;
        private readonly IEmailService _emailService;

        public AfastamentosController(IAfastamentoService afastamentoService, IProfessorService professorService,
            ISecretarioService secretarioService, IEmailService emailService,
            IUserService<Pessoa> userService, IMapper mapper, INotificator notificator)
            : base(userService, mapper, notificator)
        {
            _afastamentoService = afastamentoService;
            _professorService = professorService;
            _secretarioService = secretarioService;
            _emailService = emailService;
        }

        [Route("/")]
        [Route("afastamentos")]
        public IActionResult Index()
        {
            var userId = UserService.GetId(User);

            var afastamentos = new AfastamentoViewModelCollection
            {
                Afastamentos = Mapper.Map<IEnumerable<AfastamentoViewModel>>(_afastamentoService.GetAllWithSolicitanteAndRelator())
            };

            afastamentos.AfastamentosAsSolicitante = afastamentos.Afastamentos
                .Where(a => a.SolicitanteId == userId);

            afastamentos.AfastamentosAsRelator = afastamentos.Afastamentos
                .Where(a => a.RelatorId == userId);

            return View(afastamentos);
        }

        [Route("afastamentos/{id:guid}")]
        public IActionResult Details(Guid id)
        {
            var afastamento = _afastamentoService.GetWithAll(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            return View(Mapper.Map<AfastamentoViewModel>(afastamento));
        }

        [Authorize(Roles = "Professor")]
        [Route("afastamentos/solicitar")]
        public IActionResult Create()
        {
            return PartialView("Modals/_CreateAfastamentoModal");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Professor")]
        [Route("afastamentos/solicitar")]
        public IActionResult Create(AfastamentoViewModel afastamentoViewModel)
        {
            ModelState.Remove("Situacao");
            ModelState.Remove("DecisaoReuniao");

            if (!ModelState.IsValid)
            {
                return PartialView("Modals/_CreateAfastamentoModal", afastamentoViewModel);
            }

            afastamentoViewModel.SolicitanteId = UserService.GetId(User);

            var afastamento = _afastamentoService.Add(Mapper.Map<Afastamento>(afastamentoViewModel));

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_CreateAfastamentoModal", afastamentoViewModel);
            }

            TempData["Success"] = "Afastamento criado com sucesso!";

            return JsonOk(Url.Action(nameof(Details), new { id = afastamento.Id }));
        }

        [Authorize(Roles = "Professor")]
        [Route("afastamentos/{id:guid}/cancelar")]
        public IActionResult CancelarAfastamento(Guid id)
        {
            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            if (!IsOwnerOfId(afastamento.SolicitanteId))
            {
                return Forbid();
            }

            return PartialView("Modals/_CancelarAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
        }

        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Professor")]
        [Route("afastamentos/{id:guid}/cancelar")]
        [HttpPost, ActionName("CancelarAfastamento")]
        public IActionResult CancelarAfastamentoConfirmed(Guid id)
        {
            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            if (!IsOwnerOfId(afastamento.SolicitanteId))
            {
                return Forbid();
            }

            _afastamentoService.Cancelar(afastamento.Id);

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_CancelarAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
            }

            return JsonOk(Url.Action(nameof(Details), new { id }));
        }

        [Authorize(Roles = "Secretario")]
        [Route("afastamentos/{id:guid}/arquivar")]
        public IActionResult ArquivarAfastamento(Guid id)
        {
            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            return PartialView("Modals/_ArquivarAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
        }

        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Secretario")]
        [Route("afastamentos/{id:guid}/arquivar")]
        [HttpPost, ActionName("ArquivarAfastamento")]
        public IActionResult ArquivarAfastamentoConfirmed(Guid id)
        {
            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            _afastamentoService.Arquivar(afastamento.Id);

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_ArquivarAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
            }

            return JsonOk(Url.Action(nameof(Details), new { id }));
        }

        [Authorize(Roles = "Secretario")]
        [Route("afastamentos/{id:guid}/desbloquear")]
        public IActionResult DesbloquearAfastamento(Guid id)
        {
            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            return PartialView("Modals/_DesbloquearAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
        }

        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Secretario")]
        [Route("afastamentos/{id:guid}/desbloquear")]
        [HttpPost, ActionName("DesbloquearAfastamento")]
        public IActionResult DesbloquearAfastamentoConfirmed(Guid id, AfastamentoViewModel afastamentoViewModel)
        {
            if (id != afastamentoViewModel.Id)
            {
                return NotFound();
            }

            var afastamento = _afastamentoService.Get(afastamentoViewModel.Id);

            if (afastamento == null)
            {
                return NotFound();
            }

            _afastamentoService.Desbloquear(id, afastamentoViewModel.DecisaoReuniao == 1);

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_DesbloquearAfastamentoModal", Mapper.Map<AfastamentoViewModel>(afastamento));
            }

            return JsonOk(Url.Action(nameof(Details), new { id }));
        }

        [Authorize(Roles = "Professor")]
        [Route("afastamentos/{id:guid}/encaminhar")]
        public IActionResult EncaminharAfastamento(Guid id)
        {
            var chefe = _professorService.Get(UserService.GetId(User));

            if (!_professorService.IsChefe(chefe))
            {
                return Forbid();
            }

            var afastamento = _afastamentoService.Get(id);

            if (afastamento == null)
            {
                return NotFound();
            }

            var afastamentoViewModel = Mapper.Map<AfastamentoViewModel>(afastamento);

            if (afastamentoViewModel.RelatorId != null)
            {
                ViewBag.SelectDisabled = true;
                ModelState.AddModelError("RelatorId", "Um relator já foi definido.");
            }
            else
            {
                ViewBag.SelectDisabled = false;
            }

            return EncaminharAfastamentoModal(afastamentoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Professor")]
        [Route("afastamentos/{id:guid}/encaminhar")]
        public IActionResult EncaminharAfastamento(Guid id, AfastamentoViewModel afastamentoViewModel)
        {
            if (id != afastamentoViewModel.Id)
            {
                return NotFound();
            }

            if (String.IsNullOrEmpty(afastamentoViewModel.RelatorId))
            {
                ModelState.AddModelError("RelatorId", "O campo Relator é obrigatório.");
                return EncaminharAfastamentoModal(afastamentoViewModel);
            }

            _afastamentoService.Encaminhar(id, afastamentoViewModel.RelatorId);

            if (ErrorsOccurred())
            {
                return EncaminharAfastamentoModal(afastamentoViewModel);
            }

            return JsonOk(Url.Action(nameof(Details), new { id }));
        }

        private IActionResult EncaminharAfastamentoModal(AfastamentoViewModel afastamentoViewModel)
        {
            ViewBag.RelatorId = SelectListRelatores(afastamentoViewModel.SolicitanteId);
            return PartialView("Modals/_EncaminharAfastamentoModal", afastamentoViewModel);
        }

        private SelectList SelectListRelatores(string solicitanteId)
        {
            var chefe = _professorService.GetChefe();
            var solicitante = _professorService.GetWithParentescos(solicitanteId);

Project/Code/SCAP/Views/Afastamentos/Modals/_ArquivarAfastamentoModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="ArquivarAfastamento">
    <div class="modal-header">
        <h5 class="modal-title">Arquivar pedido de afastamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p class="text-danger m-0">Tem certeza que deseja arquivar este pedido de afastamento?</p>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Não" />
        <input type="submit" class="btn btn-danger" value="Sim" />
    </div>
</form>

Project/Code/SCAP/Views/Afastamentos/Modals/_CancelarAfastamentoModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="CancelarAfastamento">
    <div class="modal-header">
        <h5 class="modal-title">Cancelar pedido de afastamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p class="text-danger m-0">Tem certeza que deseja cancelar este pedido de afastamento?</p>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Não" />
        <input type="submit" class="btn btn-danger" value="Sim" />
    </div>
</form>

Project/Code/SCAP/Views/Afastamentos/Modals/_ConfirmarSubmissaoDocumentosModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="ConfirmarSubmissaoDocumentos">
    <div class="modal-header">
        <h5 class="modal-title">Confirmar a submissão de documentos</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p class="m-0">Tem certeza que já submeteu todos os documentos necessários?</p>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Não" />
        <input type="submit" class="btn btn-primary" value="Sim" />
    </div>
</form>

Project/Code/SCAP/Views/Afastamentos/Modals/_CreateAfastamentoModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="Create">
    <div class="modal-header">
        <h5 class="modal-title">Novo afastamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <div class="form-group">
            <label asp-for="NomeEvento" class="control-label"></label>
            <input asp-for="NomeEvento" class="form-control" />
            <span asp-validation-for="NomeEvento" class="text-danger"></span>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="DataInicio" class="control-label"></label>
                    <input asp-for="DataInicio" type="date" class="form-control" />
                    <span asp-validation-for="DataInicio" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="DataFim" class="control-label"></label>
                    <input asp-for="DataFim" type="date" class="form-control" />
                    <span asp-validation-for="DataFim" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="TipoAfastamento" class="control-label"></label><br />
                    <select class="custom-select" asp-for="TipoAfastamento">
                        <option value="1">Nacional</option>
                        <option value="2">Internacional</option>
                    </select>
                    <span asp-validation-for="TipoAfastamento" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="Onus" class="control-label"></label><br />
                    <select class="custom-select" asp-for="Onus">
                        <option value="1">Total</option>
                        <option value="2">Parcial</option>
                        <option value="2">Inexistente</option>
                    </select>
                    <span asp-validation-for="Onus" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="DataInicioEvento" class="control-label"></label>
                    <input asp-for="DataInicioEvento" type="date" class="form-control" />
                    <span asp-validation-for="DataInicioEvento" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label asp-for="DataFimEvento" class="control-label"></label>
                    <input asp-for="DataFimEvento" type="date" class="form-control" />
                    <span asp-validation-for="DataFimEvento" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Motivo" class="control-label"></label>
            <textarea rows="5" asp-for="Motivo" class="form-control"></textarea>
            <span asp-validation-for="Motivo" class="text-danger"></span>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Salvar" disabled="@ViewBag.SelectDisabled" />
    </div>
</form>

Project/Code/SCAP/Views/Afastamentos/Modals/_DesbloquearAfastamentoModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="DesbloquearAfastamento">
    <div class="modal-header">
        <h5 class="modal-title">Desbloquear pedido de afastamento</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p>Informe a decisão tomada durante a reunião do DI.</p>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="DecisaoReuniao" class="control-label"></label><br />
            <select id="select-decisao-reuniao"
                    class="form-control"
                    asp-for="DecisaoReuniao">
                <option disabled selected value=""></option>
                <option value="1">Aprovar pedido</option>
                <option value="2">Reprovar pedido</option>
            </select>
            <span asp-validation-for="DecisaoReuniao" class="text-danger"></span>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Desbloquear" />
    </div>
</form>

Project/Code/SCAP/Views/Afastamentos/Modals/_EncaminharAfastamentoModal.cshtml
@model SCAP.ViewModels.AfastamentoViewModel

<form asp-controller="Afastamentos" asp-action="EncaminharAfastamento">
    <div class="modal-header">
        <h5 class="modal-title">Definir relator</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="SolicitanteId" />
        <div class="form-group">
            <label asp-for="RelatorId" class="control-label"></label>
            <select id="select-relator"
                    class="form-control"
                    asp-for="RelatorId"
                    asp-items="ViewBag.RelatorId" disabled="@ViewBag.SelectDisabled"></select>
            <span asp-validation-for="RelatorId" class="text-danger"></span>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Salvar" disabled="@ViewBag.SelectDisabled"/>
    </div>
</form>