Project/Code/SCAP/Models/Mandato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SCAP.Models
{
    public class Mandato : Entity
    {
        [Required]
        public DateTime DataInicio { get; set; }

        [Required]
        public DateTime DataFim { get; set; }

        [Required]
        public TipoMandato TipoMandato { get; set; }

        [Required]
        [DefaultValue(false)]
        public bool Interrompido { get; set; }

        /* EF Associations */
        [Required]
        public string ProfessorId { get; set; }
        public Professor Professor { get; set; }
    }
}

Project/Code/SCAP/ViewModels/MandatoViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SCAP.ViewModels
{
    public class MandatoViewModel
    {
        [Key]
        [HiddenInput]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data de início do mandato")]
        public DateTime DataInicio { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Data de fim do mandato")]
        public DateTime DataFim { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Tipo de mandato")]
        [Range(1, 2, ErrorMessage = "O campo {0} precisa ser igual a Chefe ou Subchefe")]
        public int TipoMandato { get; set; }

        [DefaultValue(false)]
        public bool Interrompido { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [DisplayName("Professor")]
        public string ProfessorId { get; set; }
        public UserViewModel Professor { get; set; }
    }
}

Project/Code/SCAP/Controllers/MandatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SCAP.Extensions;
using SCAP.Models;
using SCAP.Notifications;
using SCAP.Services.Interfaces;
using SCAP.ViewModels;

namespace SCAP.Controllers
{
    [Authorize, ActiveUser]
    public class MandatosController : BaseController
    {
        private readonly IMandatoService _mandatoService;
        private readonly IProfessorService _professorService;

        public MandatosController(IMandatoService mandatoService, IProfessorService professorService,
            IUserService<Pessoa> userService, IMapper mapper, INotificator notificator)
            : base(userService, mapper, notificator)
        {
            _mandatoService = mandatoService;
            _professorService = professorService;
        }

        [Route("mandatos")]
        public IActionResult Index()
        {
            var today = DateTime.Now.Date;
            var vigentes = Mapper.Map<IEnumerable<MandatoViewModel>>(_mandatoService.GetMandatosVigentes());
            var mandatos = Mapper.Map<IEnumerable<MandatoViewModel>>(_mandatoService.GetAllWithProfessor());

            var mandatoViewModelCollection = new MandatoViewModelCollection
            {
                Chefes = vigentes,
                Agendados = mandatos.Where(m => m.DataInicio.Date > today),
                Arquivados = mandatos.Where(m => m.DataFim.Date < today || m.Interrompido)
            };

            return View(mandatoViewModelCollection);
        }

        [Authorize(Roles = "Secretario")]
        [Route("mandatos/novo")]
        public IActionResult Create()
        {
            return ModalCreate();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Secretario")]
        [Route("mandatos/novo")]
        public IActionResult Create(MandatoViewModel mandatoViewModel)
        {
            if (!ModelState.IsValid)
            {
                return ModalCreate(mandatoViewModel);
            }

            _mandatoService.Add(Mapper.Map<Mandato>(mandatoViewModel));

            if (ErrorsOccurred())
            {
                return ModalCreate(mandatoViewModel);
            }

            TempData["Success"] = "Mandato criado com sucesso!";

            return JsonOk(Url.Action(nameof(Index)));
        }

        private IActionResult ModalCreate(MandatoViewModel mandatoViewModel = null)
        {
            var professores = _professorService.GetAll()
                .Where(p => p.Ativo)
                .Select(p => new { p.Id, Label = $"{p.UserName} - {p.Nome} {p.Sobrenome}" });
            
            ViewBag.ProfessorId = new SelectList(professores, "Id", "Label", mandatoViewModel?.ProfessorId);

            var now = DateTime.Now.Date;

            return PartialView("Modals/_CreateMandatoModal", mandatoViewModel ?? new MandatoViewModel
            {
                DataInicio = now,
                DataFim = now.AddYears(2).AddDays(-1)
            });
        }

        [Authorize(Roles = "Secretario")]
        [Route("mandatos/{id:guid}/interromper")]
        public IActionResult Interromper(Guid id)
        {
            var mandato = _mandatoService.Get(id);

            if (mandato == null)
            {
                return NotFound();
            }

            return PartialView("Modals/_InterromperMandatoModal", Mapper.Map<MandatoViewModel>(mandato));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = "Secretario")]
        [ActionName("Interromper")]
        [Route("mandatos/{id:guid}/interromper")]
        public IActionResult InterromperConfirmed(Guid id)
        {
            var mandato = _mandatoService.GetWithProfessor(id);

            if (mandato == null)
            {
                return NotFound();
            }

            _mandatoService.Interromper(id);

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_InterromperMandatoModal", Mapper.Map<MandatoViewModel>(mandato));
            }

            TempData["Success"] = "Mandato finalizado com sucesso!";

            return JsonOk(Url.Action(nameof(Index)));
        }

        [Authorize(Roles = "Secretario")]
        [Route("mandatos/{id:guid}/excluir")]
        public IActionResult Delete(Guid id)
        {
            var mandato = _mandatoService.Get(id);

            if (mandato == null)
            {
                return NotFound();
            }

            return PartialView("Modals/_DeleteMandatoModal", Mapper.Map<MandatoViewModel>(mandato));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [Authorize(Roles = "Secretario")]
        [ActionName("Delete")]
        [Route("mandatos/{id:guid}/excluir")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var mandato = _mandatoService.GetWithProfessor(id);

            if (mandato == null)
            {
                return NotFound();
            }

            _mandatoService.Remove(id);

            if (ErrorsOccurred())
            {
                return PartialView("Modals/_DeleteMandatoModal", Mapper.Map<MandatoViewModel>(mandato));
            }

            TempData["Success"] = "Mandato excluído com sucesso!";

            return JsonOk(Url.Action(nameof(Index)));
        }
    }
}

Project/Code/SCAP/Views/Mandatos/Modals/_CreateMandatoModal.cshtml
@model SCAP.ViewModels.MandatoViewModel

<form asp-controller="Mandatos" asp-action="Create">
    <div class="modal-header">
        <h5 class="modal-title">Novo mandato</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <div class="form-group">
            <label asp-for="DataInicio" class="control-label"></label>
            <input class="form-control" type="date" asp-for="DataInicio">
            <span asp-validation-for="DataInicio" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DataFim" class="control-label"></label>
            <input class="form-control" type="date" asp-for="DataFim">
            <span asp-validation-for="DataFim" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="TipoMandato" class="control-label"></label><br />
            <select id="select-tipo-mandato" class="form-control" asp-for="TipoMandato">
                <option disabled selected value=""></option>
                <option value="1">Chefe</option>
                <option value="2">Subchefe</option>
            </select>
            <span asp-validation-for="TipoMandato" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ProfessorId" class="control-label"></label><br />
            <select id="select-chefe"
                    class="form-control"
                    asp-for="ProfessorId"
                    asp-items="@ViewBag.ProfessorId">
                <option disabled selected value=""></option>
            </select>
            <span asp-validation-for="ProfessorId" class="text-danger"></span>
        </div>
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-primary" value="Salvar" />
    </div>
</form>

Project/Code/SCAP/Views/Mandatos/Modals/_DeleteMandatoModal.cshtml
@model SCAP.ViewModels.MandatoViewModel

<form asp-controller="Mandatos" asp-action="Delete">
    <div class="modal-header">
        <h5 class="modal-title">Excluir mandato</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p class="text-danger m-0">Tem certeza que deseja excluir este mandato?<br />Essa operação não poderá ser desfeita!</p>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-danger" value="Excluir" />
    </div>
</form>

Project/Code/SCAP/Views/Mandatos/Modals/_InterromperMandatoModal.cshtml
@model SCAP.ViewModels.MandatoViewModel

<form asp-controller="Mandatos" asp-action="Interromper">
    <div class="modal-header">
        <h5 class="modal-title">Interromper mandato</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <vc:summary></vc:summary>
        <p class="text-danger m-0">Tem certeza que deseja interromper este mandato?<br />Essa operação não poderá ser desfeita!</p>
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="modal-footer">
        <input type="button" class="btn btn-secondary" data-dismiss="modal" value="Cancelar" />
        <input type="submit" class="btn btn-danger" value="Interromper" />
    </div>
</form>